name: HRules CI

on:
  push:
    tags: ["v*.*.*"]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install system OCR
        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr
      - name: Install deps
        run: pip install -U pip && pip install -e .
      - name: Smoke scan examples
        run: hrules .
      - name: Build wheels
        run: python -m build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
